/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package absensiperpustakaan;

import com.placeholder.PlaceHolder;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rachman_006
 */
public class SistemAbsensiPerpustakaan extends javax.swing.JFrame {

    /**
     * Creates new form SistemAbsensiPerpustakaan
     */
    public SistemAbsensiPerpustakaan() {
        initComponents();
        // SetTitle untuk memberikan Title ke program
        setTitle("Sistem Absensi Perpustakaan By Asna Nurfadilah");
        
        // setEditable(false) agar field tidak bisa dinput user
        areaDetail.setEditable(false);
        
        // Template Text Area dengan nama variabel areaDetail
        // ******** Awal ********** //
        areaDetail.setText("Nama \t: " +
                            "\nJenis Kelamin \t: "+
                            "\nAlamat \t: "+
                            "\nE-Mail \t: "+
                            "\nAgama \t: " +
                            "\nStatus \t: "
        );
        // ******* Akhir ********** //
           
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblJenisKelamin = new javax.swing.JLabel();
        lblAgama = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        fldNama = new javax.swing.JTextField();
        rdoJkLaki = new javax.swing.JRadioButton();
        cmbAgama = new javax.swing.JComboBox<>();
        rdoJkPerempuan = new javax.swing.JRadioButton();
        fldAlamat = new javax.swing.JTextField();
        fldEmail = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        lblUlang = new javax.swing.JButton();
        lblKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDetail = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(421, 464));
        setMinimumSize(new java.awt.Dimension(421, 464));
        setPreferredSize(new java.awt.Dimension(421, 464));
        setResizable(false);
        setSize(new java.awt.Dimension(421, 464));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle.setText("Sistem Absensi Perpustakaan");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 22, -1, -1));

        lblNama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNama.setText("Nama");
        getContentPane().add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 81, 20));

        lblJenisKelamin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblJenisKelamin.setText("Jenis Kelamin");
        getContentPane().add(lblJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        lblAgama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAgama.setText("Agama");
        getContentPane().add(lblAgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, 20));

        lblAlamat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAlamat.setText("Alamat");
        getContentPane().add(lblAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 20));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setText("E-Mail");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, 20));

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStatus.setText("Status");
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, 20));
        getContentPane().add(fldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 250, -1));

        rdoJkLaki.setText("Laki - Laki");
        getContentPane().add(rdoJkLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, 30));

        cmbAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Islam", "Kristen", "Katolik", "Buddha", "Konghucu" }));
        getContentPane().add(cmbAgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 94, -1));

        rdoJkPerempuan.setText("Perempuan");
        getContentPane().add(rdoJkPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, 30));
        getContentPane().add(fldAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 250, -1));
        getContentPane().add(fldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 250, -1));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Siswa", "Mahasiswa", "Umum" }));
        getContentPane().add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, -1));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        lblUlang.setText("Ulang");
        lblUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblUlangActionPerformed(evt);
            }
        });
        getContentPane().add(lblUlang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        lblKeluar.setText("Keluar");
        lblKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(lblKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        areaDetail.setColumns(20);
        areaDetail.setRows(5);
        jScrollPane1.setViewportView(areaDetail);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 350, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // String Dibawah untuk menampung data dari variabel lain
        String jenisKelamin, pilihAgama, pilihStatus, asnaNf1, asnaNf2, asnaNf3, asnaNf4;
        
        // if else untuk JOptionPane untuk memberikan pesan error ketika user tidak mengisi field
        if (fldNama.getText().equals("")) {
            // Pesan Dialog Ketika user tidak mengisi field akan ada informasi error ketika sudahklik tombol Simpan
            JOptionPane.showMessageDialog(null, "Harap Masukan Nama Anda !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldAlamat.getText().equals("")) {
            // Pesan Dialog Ketika user tidak mengisi field akan ada informasi error ketika sudahklik tombol Simpan
            JOptionPane.showMessageDialog(null, "Harap Masukan Alamat Anda !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldEmail.getText().equals("")) {
            // Pesan Dialog Ketika user tidak mengisi field akan ada informasi error ketika sudahklik tombol Simpan
            JOptionPane.showMessageDialog(null, "Harap Masukan E-Mail Anda !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
                // Variabel AsnaNf1 akan menampung data dari variabel fldNama 
                asnaNf1 = fldNama.getText();
                // if else dibawah untuk menentukan apakah user laki -laki atau perempuan
                if (rdoJkLaki.isSelected()){
                    // Variabel jenisKelamin akan menampung data dari variabel rdoJkLaki
                    jenisKelamin = rdoJkLaki.getText();
                }else{
                    // Variabel jenisKelamin akan menampung data dari variabel rdoJkPerempuan
                    jenisKelamin = rdoJkPerempuan.getText();
                }
                // variabel pilihAgama untuk menampung data dari variabel cmbAgama saat di pilih user dari combobox
                pilihAgama = cmbAgama.getSelectedItem().toString();
                // Variabel AsnaNf2 asnaNf3 akan menampung data dari variabel fldAlamat dan fldEmail
                asnaNf2 = fldAlamat.getText();
                asnaNf3 = fldEmail.getText();
                // variabel pilih status untuk menampung data dari variabel cmbStatus saat di pilih user dari combobox
                pilihStatus = cmbStatus.getSelectedItem().toString();
        
                // Text Area dengan nama variabel areaDetail akan di akan mmenampilkan data setelah user menekan tombol simpan
                // ******** Awal ********** //
                areaDetail.setText("Nama \t: "+ asnaNf1 +
                            "\nJenis Kelamin \t: "+ jenisKelamin +
                            "\nAlamat \t: "+ asnaNf2 +
                            "\nE-Mail \t: "+ asnaNf3 +
                            "\nAgama \t: " + pilihAgama +
                            "\nStatus \t: " + pilihStatus
                );
                // ******** Akhir ********
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void lblUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblUlangActionPerformed
        // variabel fldNama sampai fldEmail akan menset ulang semua variabel untuk menghapus semua data
        // ******** Awal **********
        fldNama.setText("");
        rdoJkLaki.setSelected(false);
        rdoJkPerempuan.setSelected(false);
        fldAlamat.setText("");
        fldEmail.setText("");
        // ******* Akhir *********
    }//GEN-LAST:event_lblUlangActionPerformed

    private void lblKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblKeluarActionPerformed
        // perintah dibawah ketika user klik maka user langsung keluar dari program
        System.exit(0);
    }//GEN-LAST:event_lblKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemAbsensiPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemAbsensiPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemAbsensiPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemAbsensiPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemAbsensiPerpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDetail;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbAgama;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JTextField fldAlamat;
    private javax.swing.JTextField fldEmail;
    private javax.swing.JTextField fldNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgama;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblJenisKelamin;
    private javax.swing.JButton lblKeluar;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton lblUlang;
    private javax.swing.JRadioButton rdoJkLaki;
    private javax.swing.JRadioButton rdoJkPerempuan;
    // End of variables declaration//GEN-END:variables
    //DefaultComboBoxModel mdl = new DefaultComboModel();

}
